import os

from dotenv import load_dotenv
import time


load_dotenv()

LOOP_INTERVAL_SECONDS = int(os.getenv("LOOP_INTERVAL_SECONDS", "300"))

GOOGLE_SPREADSHEET_ID = os.getenv("GOOGLE_SPREADSHEET_ID", "")
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_SERVICE_ACCOUNT_FILE", "")

NATURE_REMO_TOKEN = os.getenv("NATURE_REMO_TOKEN", "")
NATURE_REMO_AIRCON_ID = os.getenv("NATURE_REMO_AIRCON_ID", "")
NATURE_REMO_LIGHT_ID = os.getenv("NATURE_REMO_LIGHT_ID", "")

NATURE_REMO_LIGHT_CONTROL_METHOD = os.getenv("NATURE_REMO_LIGHT_CONTROL_METHOD", "button").lower()
NATURE_REMO_LIGHT_ON_BUTTON = os.getenv("NATURE_REMO_LIGHT_ON_BUTTON", "on")
NATURE_REMO_LIGHT_NIGHT_BUTTON = os.getenv("NATURE_REMO_LIGHT_NIGHT_BUTTON", "night")
NATURE_REMO_LIGHT_BRIGHT_UP_BUTTON = os.getenv("NATURE_REMO_LIGHT_BRIGHT_UP_BUTTON", "bright-up")
NATURE_REMO_LIGHT_BRIGHT_DOWN_BUTTON = os.getenv("NATURE_REMO_LIGHT_BRIGHT_DOWN_BUTTON", "bright-down")
NATURE_REMO_LIGHT_DAYLIGHT_BUTTON = os.getenv("NATURE_REMO_LIGHT_DAYLIGHT_BUTTON", "colortemp-up")
NATURE_REMO_LIGHT_WARM_BUTTON = os.getenv("NATURE_REMO_LIGHT_WARM_BUTTON", "colortemp-down")
NATURE_REMO_LIGHT_PLANT_BUTTON = os.getenv("NATURE_REMO_LIGHT_PLANT_BUTTON", "on-100")
NATURE_REMO_LIGHT_OFF_BUTTON = os.getenv("NATURE_REMO_LIGHT_OFF_BUTTON", "off")
NATURE_REMO_LIGHT_DAYLIGHT_SIGNAL_ID = os.getenv("NATURE_REMO_LIGHT_DAYLIGHT_SIGNAL_ID", "")
NATURE_REMO_LIGHT_WARM_SIGNAL_ID = os.getenv("NATURE_REMO_LIGHT_WARM_SIGNAL_ID", "")
NATURE_REMO_LIGHT_PLANT_SIGNAL_ID = os.getenv("NATURE_REMO_LIGHT_PLANT_SIGNAL_ID", "")
NATURE_REMO_LIGHT_OFF_SIGNAL_ID = os.getenv("NATURE_REMO_LIGHT_OFF_SIGNAL_ID", "")

OPENWEATHERMAP_API_KEY = os.getenv("OPENWEATHERMAP_API_KEY", "")
OPENWEATHERMAP_CITY = os.getenv("OPENWEATHERMAP_CITY", "Osaka,jp")

AUDIO_ENABLED = os.getenv("AUDIO_ENABLED", "false").lower() == "true"
ANNOUNCE_FILE = os.getenv("ANNOUNCE_FILE", "announce.mp3")
